"""Add Status to the Car Model

Revision ID: 3670dbb6ee28
Revises: 997b7816dfa4
Create Date: 2021-07-04 23:39:24.374327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3670dbb6ee28'
down_revision = '997b7816dfa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('status', sa.String(length=64), server_default='Active', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'status')
    # ### end Alembic commands ###
