"""Columns naming

Revision ID: 58783153e6ab
Revises: 612d19366918
Create Date: 2021-06-27 11:43:27.102937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58783153e6ab'
down_revision = '612d19366918'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('imageURL', sa.String(length=128), nullable=True))
    op.drop_column('drivers', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('image', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('drivers', 'imageURL')
    # ### end Alembic commands ###
