"""User Name can be null

Revision ID: 612d19366918
Revises: ae2e0ff500d3
Create Date: 2021-06-26 12:23:37.217215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '612d19366918'
down_revision = 'ae2e0ff500d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###
