"""Add default isSupplyPast

Revision ID: 93794561789f
Revises: a74f8e416df0
Create Date: 2021-07-24 16:22:16.101867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93794561789f'
down_revision = 'a74f8e416df0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('supplies', 'isSupplyPast',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('supplies', 'isSupplyPast',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
