"""Modify LicenseDate to LicenseExpireDate

Revision ID: 997b7816dfa4
Revises: fb47e2507e6a
Create Date: 2021-07-04 12:16:15.082563

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '997b7816dfa4'
down_revision = 'fb47e2507e6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('licenseExpireDate', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('cars', 'licenseDate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('licenseDate', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('cars', 'licenseExpireDate')
    # ### end Alembic commands ###
