"""Add supply past variable to Supply Model

Revision ID: a74f8e416df0
Revises: 974e036558b0
Create Date: 2021-07-24 16:08:35.938875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a74f8e416df0'
down_revision = '974e036558b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplies', sa.Column('isSupplyPast', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supplies', 'isSupplyPast')
    # ### end Alembic commands ###
