"""empty message

Revision ID: ae2e0ff500d3
Revises: 
Create Date: 2021-06-26 11:26:51.940392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae2e0ff500d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=64), server_default='Driver', nullable=False),
    sa.Column('image', sa.String(length=128), nullable=True),
    sa.Column('passwordResetToken', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=64), server_default='Pending', nullable=False),
    sa.Column('createdDate', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modifiedDate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('birthDate', sa.DateTime(), nullable=True),
    sa.Column('ccNumber', sa.String(length=64), nullable=True),
    sa.Column('ccExpireDate', sa.DateTime(), nullable=True),
    sa.Column('driverLicenseNumber', sa.String(length=64), nullable=True),
    sa.Column('driverLicenseExpireDate', sa.DateTime(), nullable=True),
    sa.Column('tccExpireDate', sa.DateTime(), nullable=True),
    sa.Column('camExpireDate', sa.DateTime(), nullable=True),
    sa.Column('createdDate', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modifiedDate', sa.DateTime(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drivers')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
