"""Redefine Db and add tz awareness

Revision ID: d7b2468c2975
Revises: 
Create Date: 2021-06-30 01:43:25.110347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7b2468c2975'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plate', sa.String(length=64), nullable=True),
    sa.Column('brand', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('registerDate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('chassisNo', sa.String(length=64), nullable=True),
    sa.Column('obraNo', sa.String(length=64), nullable=True),
    sa.Column('inspectionDate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tccExpireDate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('licenseDate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tachographDate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('createdDate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modifiedDate', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gasstations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('createdDate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modifiedDate', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('totalKm', sa.Integer(), nullable=False),
    sa.Column('liters', sa.Float(precision=10, decimal_return_scale=2), nullable=False),
    sa.Column('fullTank', sa.Boolean(), nullable=False),
    sa.Column('cost', sa.Float(precision=10, decimal_return_scale=2), nullable=False),
    sa.Column('supplyDate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('average', sa.Float(precision=10, decimal_return_scale=2), nullable=False),
    sa.Column('createdDate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modifiedDate', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('role', sa.String(length=64), server_default='Driver', nullable=False),
    sa.Column('image', sa.String(length=128), nullable=True),
    sa.Column('passwordResetToken', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=64), server_default='Pending', nullable=False),
    sa.Column('createdDate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modifiedDate', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('caraverages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('liters', sa.Float(precision=10, decimal_return_scale=2), nullable=False),
    sa.Column('km', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('createdDate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modifiedDate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('carId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['carId'], ['cars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imageURL', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('birthDate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ccNumber', sa.String(length=64), nullable=True),
    sa.Column('ccExpireDate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('driverLicenseNumber', sa.String(length=64), nullable=True),
    sa.Column('driverLicenseExpireDate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tccExpireDate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('camExpireDate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('createdDate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modifiedDate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drivers')
    op.drop_table('caraverages')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('supplies')
    op.drop_table('gasstations')
    op.drop_table('cars')
    # ### end Alembic commands ###
